var mime_samples = [
  { 'mime': 'application/javascript', 'samples': [
    { 'url': 'http://localhost:3000/api/', 'dir': '_m0/0', 'linked': 0, 'len': 108 },
    { 'url': 'http://localhost:3000/api.Avatar/', 'dir': '_m0/1', 'linked': 0, 'len': 52 },
    { 'url': 'http://localhost:3000/assets/color-CnuJOIlI.js', 'dir': '_m0/2', 'linked': 1, 'len': 5745 },
    { 'url': 'http://localhost:3000/assets/ErpApp-BZucdkXu.js', 'dir': '_m0/3', 'linked': 1, 'len': 141048 },
    { 'url': 'http://localhost:3000/assets/IdurarOs-BCtZVZqe.js', 'dir': '_m0/4', 'linked': 1, 'len': 379400 },
    { 'url': 'http://localhost:3000/assets/index-C4nMWe5y.js', 'dir': '_m0/5', 'linked': 2, 'len': 301366 },
    { 'url': 'http://localhost:3000/assets/index-KrFx5yLV.js', 'dir': '_m0/6', 'linked': 1, 'len': 2221 } ]
  },
  { 'mime': 'image/png', 'samples': [
    { 'url': 'http://localhost:3000/assets/favicon-Dd1eRHaG.ico', 'dir': '_m1/0', 'linked': 2, 'len': 12831 } ]
  },
  { 'mime': 'text/css', 'samples': [
    { 'url': 'http://localhost:3000/assets/About-Ca1IMYgG.js', 'dir': '_m2/0', 'linked': 1, 'len': 676 },
    { 'url': 'http://localhost:3000/assets/actions-DNtUCd0X.js', 'dir': '_m2/1', 'linked': 1, 'len': 2245 },
    { 'url': 'http://localhost:3000/assets/actions-ysozhQMY.js', 'dir': '_m2/2', 'linked': 1, 'len': 2907 },
    { 'url': 'http://localhost:3000/assets/ArrowLeftOutlined-4q-F716W.js', 'dir': '_m2/3', 'linked': 1, 'len': 524 },
    { 'url': 'http://localhost:3000/assets/calculate-DbSGk6nY.js', 'dir': '_m2/4', 'linked': 1, 'len': 206 },
    { 'url': 'http://localhost:3000/assets/CloseCircleOutlined-Bi0FNh2q.js', 'dir': '_m2/5', 'linked': 1, 'len': 1128 },
    { 'url': 'http://localhost:3000/assets/CreateItem-BzUsvAXm.js', 'dir': '_m2/6', 'linked': 1, 'len': 2042 },
    { 'url': 'http://localhost:3000/assets/CrudModule-BBK_-8xX.js', 'dir': '_m2/7', 'linked': 1, 'len': 27649 },
    { 'url': 'http://localhost:3000/assets/Dashboard-jynXsLzr.js', 'dir': '_m2/8', 'linked': 1, 'len': 9156 },
    { 'url': 'http://localhost:3000/assets/DeleteOutlined-DOr4ck-Q.js', 'dir': '_m2/9', 'linked': 1, 'len': 642 },
    { 'url': 'http://localhost:3000/assets/fade-CxtjAN5u.js', 'dir': '_m2/10', 'linked': 1, 'len': 547 },
    { 'url': 'http://localhost:3000/assets/FilePdfOutlined-CAOrmpht.js', 'dir': '_m2/11', 'linked': 1, 'len': 1372 },
    { 'url': 'http://localhost:3000/assets/helpers-BilhNsDy.js', 'dir': '_m2/12', 'linked': 1, 'len': 1383 },
    { 'url': 'http://localhost:3000/assets/index-4Ydivefu.js', 'dir': '_m2/13', 'linked': 1, 'len': 2671 },
    { 'url': 'http://localhost:3000/assets/index-6VrU-YIl.js', 'dir': '_m2/14', 'linked': 1, 'len': 23002 },
    { 'url': 'http://localhost:3000/assets/index-B5jILbcJ.js', 'dir': '_m2/15', 'linked': 1, 'len': 2788 },
    { 'url': 'http://localhost:3000/assets/index-B6jV2cQt.js', 'dir': '_m2/16', 'linked': 1, 'len': 27114 },
    { 'url': 'http://localhost:3000/assets/index-Bc3jZFJd.js', 'dir': '_m2/17', 'linked': 1, 'len': 5489 },
    { 'url': 'http://localhost:3000/assets/index-BmkYMUH-.js', 'dir': '_m2/18', 'linked': 1, 'len': 6681 },
    { 'url': 'http://localhost:3000/assets/index-C5wZysJn.js', 'dir': '_m2/19', 'linked': 1, 'len': 3808 },
    { 'url': 'http://localhost:3000/assets/index-C5XPIeeu.js', 'dir': '_m2/20', 'linked': 1, 'len': 1784 },
    { 'url': 'http://localhost:3000/assets/index-CAOdWOmb.js', 'dir': '_m2/21', 'linked': 1, 'len': 2629 },
    { 'url': 'http://localhost:3000/assets/index-CCAhvlYD.js', 'dir': '_m2/22', 'linked': 1, 'len': 3561 },
    { 'url': 'http://localhost:3000/assets/index-Ci5STuGe.js', 'dir': '_m2/23', 'linked': 1, 'len': 62345 },
    { 'url': 'http://localhost:3000/assets/index-CQ59tf3N.js', 'dir': '_m2/24', 'linked': 1, 'len': 1925 },
    { 'url': 'http://localhost:3000/assets/index-Cx6IiUbX.js', 'dir': '_m2/25', 'linked': 1, 'len': 1400 },
    { 'url': 'http://localhost:3000/assets/index-D1pTFRzE.js', 'dir': '_m2/26', 'linked': 1, 'len': 102883 },
    { 'url': 'http://localhost:3000/assets/index-Dycg0fYR.js', 'dir': '_m2/27', 'linked': 1, 'len': 7927 },
    { 'url': 'http://localhost:3000/assets/index-DyraH4Lq.js', 'dir': '_m2/28', 'linked': 1, 'len': 74164 },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js', 'dir': '_m2/29', 'linked': 1, 'len': 15011 },
    { 'url': 'http://localhost:3000/assets/index-IHz-65YD.js', 'dir': '_m2/30', 'linked': 1, 'len': 7958 },
    { 'url': 'http://localhost:3000/assets/InvoiceCreate-eJG2MtIB.js', 'dir': '_m2/31', 'linked': 1, 'len': 1250 },
    { 'url': 'http://localhost:3000/assets/InvoiceForm-8U_iHxe2.js', 'dir': '_m2/32', 'linked': 1, 'len': 4876 },
    { 'url': 'http://localhost:3000/assets/InvoiceRead-Cy5Ix1EQ.js', 'dir': '_m2/33', 'linked': 1, 'len': 1156 },
    { 'url': 'http://localhost:3000/assets/InvoiceRecordPayment-BB_agaFE.js', 'dir': '_m2/34', 'linked': 1, 'len': 4233 },
    { 'url': 'http://localhost:3000/assets/InvoiceUpdate-BR42lIDu.js', 'dir': '_m2/35', 'linked': 1, 'len': 1573 },
    { 'url': 'http://localhost:3000/assets/Logout-BTYPVvCR.js', 'dir': '_m2/36', 'linked': 1, 'len': 389 },
    { 'url': 'http://localhost:3000/assets/PaymentForm-Ckxurmtb.js', 'dir': '_m2/37', 'linked': 1, 'len': 2153 },
    { 'url': 'http://localhost:3000/assets/PaymentRead-CbhAxth7.js', 'dir': '_m2/38', 'linked': 1, 'len': 4994 },
    { 'url': 'http://localhost:3000/assets/PlusOutlined-CUdEX3TB.js', 'dir': '_m2/39', 'linked': 1, 'len': 441 },
    { 'url': 'http://localhost:3000/assets/Profile-BxsFADUT.js', 'dir': '_m2/40', 'linked': 1, 'len': 101452 },
    { 'url': 'http://localhost:3000/assets/progress-Dvk-IPrI.js', 'dir': '_m2/41', 'linked': 1, 'len': 14966 },
    { 'url': 'http://localhost:3000/assets/ReadItem-BP4gut0_.js', 'dir': '_m2/42', 'linked': 1, 'len': 5760 },
    { 'url': 'http://localhost:3000/assets/selectors-DquMLP7b.js', 'dir': '_m2/43', 'linked': 1, 'len': 676 },
    { 'url': 'http://localhost:3000/assets/Settings-IMAzynxH.js', 'dir': '_m2/44', 'linked': 1, 'len': 53929 },
    { 'url': 'http://localhost:3000/assets/Table-pdXRWxgE.js', 'dir': '_m2/45', 'linked': 1, 'len': 180809 },
    { 'url': 'http://localhost:3000/assets/UpdateItem-C8DyAT9O.js', 'dir': '_m2/46', 'linked': 1, 'len': 2423 },
    { 'url': 'http://localhost:3000/assets/UploadOutlined-DsxgGjnA.js', 'dir': '_m2/47', 'linked': 1, 'len': 41284 },
    { 'url': 'http://localhost:3000/assets/useDate-BK7OBCbi.js', 'dir': '_m2/48', 'linked': 1, 'len': 200 },
    { 'url': 'http://localhost:3000/assets/useDebounce-BuyoAkM0.js', 'dir': '_m2/49', 'linked': 1, 'len': 514 },
    { 'url': 'http://localhost:3000/assets/useFetch-CPBJnrcm.js', 'dir': '_m2/50', 'linked': 1, 'len': 440 },
    { 'url': 'http://localhost:3000/assets/useMail-B8yAc_AL.js', 'dir': '_m2/51', 'linked': 1, 'len': 282 },
    { 'url': 'http://localhost:3000/assets/useMoney-5XCsrR9m.js', 'dir': '_m2/52', 'linked': 1, 'len': 4088 } ]
  },
  { 'mime': 'text/html', 'samples': [
    { 'url': 'http://localhost:3000/', 'dir': '_m3/0', 'linked': 2, 'len': 692 },
    { 'url': 'http://localhost:3000/%0A%0A0%8B%A6%0D%B8/', 'dir': '_m3/1', 'linked': 0, 'len': 157 },
    { 'url': 'http://localhost:3000/assets/', 'dir': '_m3/2', 'linked': 2, 'len': 153 } ]
  },
  { 'mime': 'text/plain', 'samples': [
    { 'url': 'http://localhost:3000/assets/index-Dp7q_7To.css', 'dir': '_m4/0', 'linked': 2, 'len': 6449 } ]
  }
];

var issue_samples = [
  { 'severity': 3, 'type': 40401, 'samples': [
    { 'url': 'http://localhost:3000/assets/index-Dp7q_7To.css', 'extra': 'Delimited database dump', 'sid': '0', 'dir': '_i0/0' } ]
  },
  { 'severity': 1, 'type': 20301, 'samples': [
    { 'url': 'http://localhost:3000/assets/null', 'extra': '', 'sid': '0', 'dir': '_i1/0' } ]
  },
  { 'severity': 0, 'type': 10901, 'samples': [
    { 'url': 'http://localhost:3000/%0A%0A0%8B%A6%0D%B8/', 'extra': '', 'sid': '0', 'dir': '_i2/0' },
    { 'url': 'http://localhost:3000/assets/About-Ca1IMYgG.js', 'extra': '', 'sid': '0', 'dir': '_i2/1' },
    { 'url': 'http://localhost:3000/assets/actions-DNtUCd0X.js', 'extra': '', 'sid': '0', 'dir': '_i2/2' },
    { 'url': 'http://localhost:3000/assets/ArrowLeftOutlined-4q-F716W.js', 'extra': '', 'sid': '0', 'dir': '_i2/3' },
    { 'url': 'http://localhost:3000/assets/calculate-DbSGk6nY.js', 'extra': '', 'sid': '0', 'dir': '_i2/4' },
    { 'url': 'http://localhost:3000/assets/CloseCircleOutlined-Bi0FNh2q.js', 'extra': '', 'sid': '0', 'dir': '_i2/5' },
    { 'url': 'http://localhost:3000/assets/CrudModule-BBK_-8xX.js', 'extra': '', 'sid': '0', 'dir': '_i2/6' },
    { 'url': 'http://localhost:3000/assets/DeleteOutlined-DOr4ck-Q.js', 'extra': '', 'sid': '0', 'dir': '_i2/7' },
    { 'url': 'http://localhost:3000/assets/fade-CxtjAN5u.js', 'extra': '', 'sid': '0', 'dir': '_i2/8' },
    { 'url': 'http://localhost:3000/assets/index-4Ydivefu.js', 'extra': '', 'sid': '0', 'dir': '_i2/9' },
    { 'url': 'http://localhost:3000/assets/index-6VrU-YIl.js', 'extra': '', 'sid': '0', 'dir': '_i2/10' },
    { 'url': 'http://localhost:3000/assets/index-B5jILbcJ.js', 'extra': '', 'sid': '0', 'dir': '_i2/11' },
    { 'url': 'http://localhost:3000/assets/index-B6jV2cQt.js', 'extra': '', 'sid': '0', 'dir': '_i2/12' },
    { 'url': 'http://localhost:3000/assets/index-Bc3jZFJd.js', 'extra': '', 'sid': '0', 'dir': '_i2/13' },
    { 'url': 'http://localhost:3000/assets/index-C4nMWe5y.js', 'extra': '', 'sid': '0', 'dir': '_i2/14' },
    { 'url': 'http://localhost:3000/assets/index-C5wZysJn.js', 'extra': '', 'sid': '0', 'dir': '_i2/15' },
    { 'url': 'http://localhost:3000/assets/index-C5XPIeeu.js', 'extra': '', 'sid': '0', 'dir': '_i2/16' },
    { 'url': 'http://localhost:3000/assets/index-Ci5STuGe.js', 'extra': '', 'sid': '0', 'dir': '_i2/17' },
    { 'url': 'http://localhost:3000/assets/index-CQ59tf3N.js', 'extra': '', 'sid': '0', 'dir': '_i2/18' },
    { 'url': 'http://localhost:3000/assets/index-Cx6IiUbX.js', 'extra': '', 'sid': '0', 'dir': '_i2/19' },
    { 'url': 'http://localhost:3000/assets/index-D1pTFRzE.js', 'extra': '', 'sid': '0', 'dir': '_i2/20' },
    { 'url': 'http://localhost:3000/assets/index-Dp7q_7To.css', 'extra': '', 'sid': '0', 'dir': '_i2/21' },
    { 'url': 'http://localhost:3000/assets/index-Dycg0fYR.js', 'extra': '', 'sid': '0', 'dir': '_i2/22' },
    { 'url': 'http://localhost:3000/assets/index-DyraH4Lq.js', 'extra': '', 'sid': '0', 'dir': '_i2/23' },
    { 'url': 'http://localhost:3000/assets/index-IHz-65YD.js', 'extra': '', 'sid': '0', 'dir': '_i2/24' },
    { 'url': 'http://localhost:3000/assets/index-KrFx5yLV.js', 'extra': '', 'sid': '0', 'dir': '_i2/25' },
    { 'url': 'http://localhost:3000/assets/InvoiceCreate-eJG2MtIB.js', 'extra': '', 'sid': '0', 'dir': '_i2/26' },
    { 'url': 'http://localhost:3000/assets/InvoiceForm-8U_iHxe2.js', 'extra': '', 'sid': '0', 'dir': '_i2/27' },
    { 'url': 'http://localhost:3000/assets/InvoiceRead-Cy5Ix1EQ.js', 'extra': '', 'sid': '0', 'dir': '_i2/28' },
    { 'url': 'http://localhost:3000/assets/InvoiceUpdate-BR42lIDu.js', 'extra': '', 'sid': '0', 'dir': '_i2/29' },
    { 'url': 'http://localhost:3000/assets/PaymentRead-CbhAxth7.js', 'extra': '', 'sid': '0', 'dir': '_i2/30' },
    { 'url': 'http://localhost:3000/assets/PlusOutlined-CUdEX3TB.js', 'extra': '', 'sid': '0', 'dir': '_i2/31' },
    { 'url': 'http://localhost:3000/assets/ReadItem-BP4gut0_.js', 'extra': '', 'sid': '0', 'dir': '_i2/32' },
    { 'url': 'http://localhost:3000/assets/selectors-DquMLP7b.js', 'extra': '', 'sid': '0', 'dir': '_i2/33' },
    { 'url': 'http://localhost:3000/assets/UpdateItem-C8DyAT9O.js', 'extra': '', 'sid': '0', 'dir': '_i2/34' },
    { 'url': 'http://localhost:3000/assets/useDate-BK7OBCbi.js', 'extra': '', 'sid': '0', 'dir': '_i2/35' },
    { 'url': 'http://localhost:3000/assets/useDebounce-BuyoAkM0.js', 'extra': '', 'sid': '0', 'dir': '_i2/36' },
    { 'url': 'http://localhost:3000/assets/useMail-B8yAc_AL.js', 'extra': '', 'sid': '0', 'dir': '_i2/37' },
    { 'url': 'http://localhost:3000/assets/useMoney-5XCsrR9m.js', 'extra': '', 'sid': '0', 'dir': '_i2/38' } ]
  },
  { 'severity': 0, 'type': 10803, 'samples': [
    { 'url': 'http://localhost:3000/', 'extra': '', 'sid': '0', 'dir': '_i3/0' },
    { 'url': 'http://localhost:3000/%0A%0A0%8B%A6%0D%B8/', 'extra': '', 'sid': '0', 'dir': '_i3/1' },
    { 'url': 'http://localhost:3000/api/', 'extra': '', 'sid': '0', 'dir': '_i3/2' },
    { 'url': 'http://localhost:3000/api.Avatar/', 'extra': '', 'sid': '0', 'dir': '_i3/3' },
    { 'url': 'http://localhost:3000/assets/', 'extra': '', 'sid': '0', 'dir': '_i3/4' },
    { 'url': 'http://localhost:3000/assets//', 'extra': '', 'sid': '0', 'dir': '_i3/5' },
    { 'url': 'http://localhost:3000/assets/About-Ca1IMYgG.js', 'extra': '', 'sid': '0', 'dir': '_i3/6' },
    { 'url': 'http://localhost:3000/assets/actions-DNtUCd0X.js', 'extra': '', 'sid': '0', 'dir': '_i3/7' },
    { 'url': 'http://localhost:3000/assets/actions-ysozhQMY.js', 'extra': '', 'sid': '0', 'dir': '_i3/8' },
    { 'url': 'http://localhost:3000/assets/ArrowLeftOutlined-4q-F716W.js', 'extra': '', 'sid': '0', 'dir': '_i3/9' },
    { 'url': 'http://localhost:3000/assets/calculate-DbSGk6nY.js', 'extra': '', 'sid': '0', 'dir': '_i3/10' },
    { 'url': 'http://localhost:3000/assets/CloseCircleOutlined-Bi0FNh2q.js', 'extra': '', 'sid': '0', 'dir': '_i3/11' },
    { 'url': 'http://localhost:3000/assets/color-CnuJOIlI.js', 'extra': '', 'sid': '0', 'dir': '_i3/12' },
    { 'url': 'http://localhost:3000/assets/CreateItem-BzUsvAXm.js', 'extra': '', 'sid': '0', 'dir': '_i3/13' },
    { 'url': 'http://localhost:3000/assets/CrudModule-BBK_-8xX.js', 'extra': '', 'sid': '0', 'dir': '_i3/14' },
    { 'url': 'http://localhost:3000/assets/Dashboard-jynXsLzr.js', 'extra': '', 'sid': '0', 'dir': '_i3/15' },
    { 'url': 'http://localhost:3000/assets/DeleteOutlined-DOr4ck-Q.js', 'extra': '', 'sid': '0', 'dir': '_i3/16' },
    { 'url': 'http://localhost:3000/assets/ErpApp-BZucdkXu.js', 'extra': '', 'sid': '0', 'dir': '_i3/17' },
    { 'url': 'http://localhost:3000/assets/ErpApp-BZucdkXu.js?v=9876sfi', 'extra': '', 'sid': '0', 'dir': '_i3/18' },
    { 'url': 'http://localhost:3000/assets/fade-CxtjAN5u.js', 'extra': '', 'sid': '0', 'dir': '_i3/19' },
    { 'url': 'http://localhost:3000/assets/favicon-Dd1eRHaG.ico', 'extra': '', 'sid': '0', 'dir': '_i3/20' },
    { 'url': 'http://localhost:3000/assets/FilePdfOutlined-CAOrmpht.js', 'extra': '', 'sid': '0', 'dir': '_i3/21' },
    { 'url': 'http://localhost:3000/assets/helpers-BilhNsDy.js', 'extra': '', 'sid': '0', 'dir': '_i3/22' },
    { 'url': 'http://localhost:3000/assets/IdurarOs-BCtZVZqe.js', 'extra': '', 'sid': '0', 'dir': '_i3/23' },
    { 'url': 'http://localhost:3000/assets/index-4Ydivefu.js', 'extra': '', 'sid': '0', 'dir': '_i3/24' },
    { 'url': 'http://localhost:3000/assets/index-6VrU-YIl.js', 'extra': '', 'sid': '0', 'dir': '_i3/25' },
    { 'url': 'http://localhost:3000/assets/index-B5jILbcJ.js', 'extra': '', 'sid': '0', 'dir': '_i3/26' },
    { 'url': 'http://localhost:3000/assets/index-B6jV2cQt.js', 'extra': '', 'sid': '0', 'dir': '_i3/27' },
    { 'url': 'http://localhost:3000/assets/index-Bc3jZFJd.js', 'extra': '', 'sid': '0', 'dir': '_i3/28' },
    { 'url': 'http://localhost:3000/assets/index-BmkYMUH-.js', 'extra': '', 'sid': '0', 'dir': '_i3/29' },
    { 'url': 'http://localhost:3000/assets/index-C4nMWe5y.js', 'extra': '', 'sid': '0', 'dir': '_i3/30' },
    { 'url': 'http://localhost:3000/assets/index-C5wZysJn.js', 'extra': '', 'sid': '0', 'dir': '_i3/31' },
    { 'url': 'http://localhost:3000/assets/index-C5XPIeeu.js', 'extra': '', 'sid': '0', 'dir': '_i3/32' },
    { 'url': 'http://localhost:3000/assets/index-CAOdWOmb.js', 'extra': '', 'sid': '0', 'dir': '_i3/33' },
    { 'url': 'http://localhost:3000/assets/index-CCAhvlYD.js', 'extra': '', 'sid': '0', 'dir': '_i3/34' },
    { 'url': 'http://localhost:3000/assets/index-Ci5STuGe.js', 'extra': '', 'sid': '0', 'dir': '_i3/35' },
    { 'url': 'http://localhost:3000/assets/index-Ci5STuGe.js?Rr:Ar;Mr.useSyncExternalStore=se.useSyncExternalStore!=9876sfi', 'extra': '', 'sid': '0', 'dir': '_i3/36' },
    { 'url': 'http://localhost:3000/assets/index-Ci5STuGe.js?9876sfi;Mr.useSyncExternalStore=se.useSyncExternalStore!=%3Dvoid', 'extra': '', 'sid': '0', 'dir': '_i3/37' },
    { 'url': 'http://localhost:3000/assets/index-Ci5STuGe.js?Rr:Ar;Mr.useSyncExternalStore=9876sfi!=%3Dvoid', 'extra': '', 'sid': '0', 'dir': '_i3/38' },
    { 'url': 'http://localhost:3000/assets/index-CQ59tf3N.js', 'extra': '', 'sid': '0', 'dir': '_i3/39' },
    { 'url': 'http://localhost:3000/assets/index-Cx6IiUbX.js', 'extra': '', 'sid': '0', 'dir': '_i3/40' },
    { 'url': 'http://localhost:3000/assets/index-D1pTFRzE.js', 'extra': '', 'sid': '0', 'dir': '_i3/41' },
    { 'url': 'http://localhost:3000/assets/index-Dp7q_7To.css', 'extra': '', 'sid': '0', 'dir': '_i3/42' },
    { 'url': 'http://localhost:3000/assets/index-Dycg0fYR.js', 'extra': '', 'sid': '0', 'dir': '_i3/43' },
    { 'url': 'http://localhost:3000/assets/index-DyraH4Lq.js', 'extra': '', 'sid': '0', 'dir': '_i3/44' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js', 'extra': '', 'sid': '0', 'dir': '_i3/45' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?9876sfi;E.Button=ue;E.Avatar=ce;E.Input=me;E.Image=de;E.Node=$e;const', 'extra': '', 'sid': '0', 'dir': '_i3/46' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?c:null};E.Button=ue;E.Avatar=9876sfi;E.Input=me;E.Image=de;E.Node=$e;const', 'extra': '', 'sid': '0', 'dir': '_i3/47' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?c:null};E.Button=9876sfi;E.Avatar=ce;E.Input=me;E.Image=de;E.Node=$e;const', 'extra': '', 'sid': '0', 'dir': '_i3/48' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?c:null};E.Button=ue;E.Avatar=ce;E.Input=me;E.Image=9876sfi;E.Node=$e;const', 'extra': '', 'sid': '0', 'dir': '_i3/49' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?c:null};E.Button=ue;E.Avatar=ce;E.Input=9876sfi;E.Image=de;E.Node=$e;const', 'extra': '', 'sid': '0', 'dir': '_i3/50' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?c:null};E.Button=ue;E.Avatar=ce;E.Input=me;E.Image=de;E.Node=9876sfi$e;const', 'extra': '', 'sid': '0', 'dir': '_i3/51' },
    { 'url': 'http://localhost:3000/assets/index-IHz-65YD.js', 'extra': '', 'sid': '0', 'dir': '_i3/52' },
    { 'url': 'http://localhost:3000/assets/index-KrFx5yLV.js', 'extra': '', 'sid': '0', 'dir': '_i3/53' },
    { 'url': 'http://localhost:3000/assets/InvoiceCreate-eJG2MtIB.js', 'extra': '', 'sid': '0', 'dir': '_i3/54' },
    { 'url': 'http://localhost:3000/assets/InvoiceForm-8U_iHxe2.js', 'extra': '', 'sid': '0', 'dir': '_i3/55' },
    { 'url': 'http://localhost:3000/assets/InvoiceRead-Cy5Ix1EQ.js', 'extra': '', 'sid': '0', 'dir': '_i3/56' },
    { 'url': 'http://localhost:3000/assets/InvoiceRecordPayment-BB_agaFE.js', 'extra': '', 'sid': '0', 'dir': '_i3/57' },
    { 'url': 'http://localhost:3000/assets/InvoiceUpdate-BR42lIDu.js', 'extra': '', 'sid': '0', 'dir': '_i3/58' },
    { 'url': 'http://localhost:3000/assets/Logout-BTYPVvCR.js', 'extra': '', 'sid': '0', 'dir': '_i3/59' },
    { 'url': 'http://localhost:3000/assets/PaymentForm-Ckxurmtb.js', 'extra': '', 'sid': '0', 'dir': '_i3/60' },
    { 'url': 'http://localhost:3000/assets/PaymentRead-CbhAxth7.js', 'extra': '', 'sid': '0', 'dir': '_i3/61' },
    { 'url': 'http://localhost:3000/assets/PlusOutlined-CUdEX3TB.js', 'extra': '', 'sid': '0', 'dir': '_i3/62' },
    { 'url': 'http://localhost:3000/assets/Profile-BxsFADUT.js', 'extra': '', 'sid': '0', 'dir': '_i3/63' },
    { 'url': 'http://localhost:3000/assets/progress-Dvk-IPrI.js', 'extra': '', 'sid': '0', 'dir': '_i3/64' },
    { 'url': 'http://localhost:3000/assets/ReadItem-BP4gut0_.js', 'extra': '', 'sid': '0', 'dir': '_i3/65' },
    { 'url': 'http://localhost:3000/assets/selectors-DquMLP7b.js', 'extra': '', 'sid': '0', 'dir': '_i3/66' },
    { 'url': 'http://localhost:3000/assets/Settings-IMAzynxH.js', 'extra': '', 'sid': '0', 'dir': '_i3/67' },
    { 'url': 'http://localhost:3000/assets/Table-pdXRWxgE.js', 'extra': '', 'sid': '0', 'dir': '_i3/68' },
    { 'url': 'http://localhost:3000/assets/UpdateItem-C8DyAT9O.js', 'extra': '', 'sid': '0', 'dir': '_i3/69' },
    { 'url': 'http://localhost:3000/assets/UploadOutlined-DsxgGjnA.js', 'extra': '', 'sid': '0', 'dir': '_i3/70' },
    { 'url': 'http://localhost:3000/assets/useDate-BK7OBCbi.js', 'extra': '', 'sid': '0', 'dir': '_i3/71' },
    { 'url': 'http://localhost:3000/assets/useDebounce-BuyoAkM0.js', 'extra': '', 'sid': '0', 'dir': '_i3/72' },
    { 'url': 'http://localhost:3000/assets/useFetch-CPBJnrcm.js', 'extra': '', 'sid': '0', 'dir': '_i3/73' },
    { 'url': 'http://localhost:3000/assets/useMail-B8yAc_AL.js', 'extra': '', 'sid': '0', 'dir': '_i3/74' },
    { 'url': 'http://localhost:3000/assets/useMoney-5XCsrR9m.js', 'extra': '', 'sid': '0', 'dir': '_i3/75' },
    { 'url': 'http://localhost:3000/assets/assets', 'extra': '', 'sid': '0', 'dir': '_i3/76' },
    { 'url': 'http://localhost:3000/assets/null', 'extra': '', 'sid': '0', 'dir': '_i3/77' },
    { 'url': 'http://localhost:3000/assets/null;a', 'extra': '', 'sid': '0', 'dir': '_i3/78' },
    { 'url': 'http://localhost:3000/assets/null;a?y=await', 'extra': '', 'sid': '0', 'dir': '_i3/79' },
    { 'url': 'http://localhost:3000/assets/null;t', 'extra': '', 'sid': '0', 'dir': '_i3/80' },
    { 'url': 'http://localhost:3000/assets/null;t?d=await', 'extra': '', 'sid': '0', 'dir': '_i3/81' },
    { 'url': 'http://localhost:3000/assets/', 'extra': '', 'sid': '0', 'dir': '_i3/82' } ]
  },
  { 'severity': 0, 'type': 10801, 'samples': [
    { 'url': 'http://localhost:3000/assets/About-Ca1IMYgG.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/0' },
    { 'url': 'http://localhost:3000/assets/actions-DNtUCd0X.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/1' },
    { 'url': 'http://localhost:3000/assets/actions-ysozhQMY.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/2' },
    { 'url': 'http://localhost:3000/assets/ArrowLeftOutlined-4q-F716W.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/3' },
    { 'url': 'http://localhost:3000/assets/calculate-DbSGk6nY.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/4' },
    { 'url': 'http://localhost:3000/assets/CloseCircleOutlined-Bi0FNh2q.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/5' },
    { 'url': 'http://localhost:3000/assets/CreateItem-BzUsvAXm.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/6' },
    { 'url': 'http://localhost:3000/assets/CrudModule-BBK_-8xX.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/7' },
    { 'url': 'http://localhost:3000/assets/Dashboard-jynXsLzr.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/8' },
    { 'url': 'http://localhost:3000/assets/DeleteOutlined-DOr4ck-Q.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/9' },
    { 'url': 'http://localhost:3000/assets/fade-CxtjAN5u.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/10' },
    { 'url': 'http://localhost:3000/assets/favicon-Dd1eRHaG.ico', 'extra': 'image/png', 'sid': '0', 'dir': '_i4/11' },
    { 'url': 'http://localhost:3000/assets/FilePdfOutlined-CAOrmpht.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/12' },
    { 'url': 'http://localhost:3000/assets/helpers-BilhNsDy.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/13' },
    { 'url': 'http://localhost:3000/assets/index-4Ydivefu.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/14' },
    { 'url': 'http://localhost:3000/assets/index-6VrU-YIl.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/15' },
    { 'url': 'http://localhost:3000/assets/index-B5jILbcJ.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/16' },
    { 'url': 'http://localhost:3000/assets/index-B6jV2cQt.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/17' },
    { 'url': 'http://localhost:3000/assets/index-Bc3jZFJd.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/18' },
    { 'url': 'http://localhost:3000/assets/index-BmkYMUH-.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/19' },
    { 'url': 'http://localhost:3000/assets/index-C5wZysJn.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/20' },
    { 'url': 'http://localhost:3000/assets/index-C5XPIeeu.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/21' },
    { 'url': 'http://localhost:3000/assets/index-CAOdWOmb.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/22' },
    { 'url': 'http://localhost:3000/assets/index-CCAhvlYD.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/23' },
    { 'url': 'http://localhost:3000/assets/index-Ci5STuGe.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/24' },
    { 'url': 'http://localhost:3000/assets/index-Ci5STuGe.js?Rr:Ar;Mr.useSyncExternalStore=se.useSyncExternalStore!=9876sfi', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/25' },
    { 'url': 'http://localhost:3000/assets/index-Ci5STuGe.js?9876sfi;Mr.useSyncExternalStore=se.useSyncExternalStore!=%3Dvoid', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/26' },
    { 'url': 'http://localhost:3000/assets/index-Ci5STuGe.js?Rr:Ar;Mr.useSyncExternalStore=9876sfi!=%3Dvoid', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/27' },
    { 'url': 'http://localhost:3000/assets/index-CQ59tf3N.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/28' },
    { 'url': 'http://localhost:3000/assets/index-Cx6IiUbX.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/29' },
    { 'url': 'http://localhost:3000/assets/index-D1pTFRzE.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/30' },
    { 'url': 'http://localhost:3000/assets/index-Dycg0fYR.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/31' },
    { 'url': 'http://localhost:3000/assets/index-DyraH4Lq.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/32' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/33' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?9876sfi;E.Button=ue;E.Avatar=ce;E.Input=me;E.Image=de;E.Node=$e;const', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/34' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?c:null};E.Button=ue;E.Avatar=9876sfi;E.Input=me;E.Image=de;E.Node=$e;const', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/35' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?c:null};E.Button=9876sfi;E.Avatar=ce;E.Input=me;E.Image=de;E.Node=$e;const', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/36' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?c:null};E.Button=ue;E.Avatar=ce;E.Input=me;E.Image=9876sfi;E.Node=$e;const', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/37' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?c:null};E.Button=ue;E.Avatar=ce;E.Input=9876sfi;E.Image=de;E.Node=$e;const', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/38' },
    { 'url': 'http://localhost:3000/assets/index-hsTGyMzD.js?c:null};E.Button=ue;E.Avatar=ce;E.Input=me;E.Image=de;E.Node=9876sfi$e;const', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/39' },
    { 'url': 'http://localhost:3000/assets/index-IHz-65YD.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/40' },
    { 'url': 'http://localhost:3000/assets/InvoiceCreate-eJG2MtIB.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/41' },
    { 'url': 'http://localhost:3000/assets/InvoiceForm-8U_iHxe2.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/42' },
    { 'url': 'http://localhost:3000/assets/InvoiceRead-Cy5Ix1EQ.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/43' },
    { 'url': 'http://localhost:3000/assets/InvoiceRecordPayment-BB_agaFE.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/44' },
    { 'url': 'http://localhost:3000/assets/InvoiceUpdate-BR42lIDu.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/45' },
    { 'url': 'http://localhost:3000/assets/Logout-BTYPVvCR.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/46' },
    { 'url': 'http://localhost:3000/assets/PaymentForm-Ckxurmtb.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/47' },
    { 'url': 'http://localhost:3000/assets/PaymentRead-CbhAxth7.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/48' },
    { 'url': 'http://localhost:3000/assets/PlusOutlined-CUdEX3TB.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/49' },
    { 'url': 'http://localhost:3000/assets/Profile-BxsFADUT.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/50' },
    { 'url': 'http://localhost:3000/assets/progress-Dvk-IPrI.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/51' },
    { 'url': 'http://localhost:3000/assets/ReadItem-BP4gut0_.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/52' },
    { 'url': 'http://localhost:3000/assets/selectors-DquMLP7b.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/53' },
    { 'url': 'http://localhost:3000/assets/Settings-IMAzynxH.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/54' },
    { 'url': 'http://localhost:3000/assets/Table-pdXRWxgE.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/55' },
    { 'url': 'http://localhost:3000/assets/UpdateItem-C8DyAT9O.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/56' },
    { 'url': 'http://localhost:3000/assets/UploadOutlined-DsxgGjnA.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/57' },
    { 'url': 'http://localhost:3000/assets/useDate-BK7OBCbi.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/58' },
    { 'url': 'http://localhost:3000/assets/useDebounce-BuyoAkM0.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/59' },
    { 'url': 'http://localhost:3000/assets/useFetch-CPBJnrcm.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/60' },
    { 'url': 'http://localhost:3000/assets/useMail-B8yAc_AL.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/61' },
    { 'url': 'http://localhost:3000/assets/useMoney-5XCsrR9m.js', 'extra': 'text/css', 'sid': '0', 'dir': '_i4/62' } ]
  },
  { 'severity': 0, 'type': 10405, 'samples': [
    { 'url': 'http://localhost:3000/%0A%0A0%8B%A6%0D%B8/', 'extra': '', 'sid': '0', 'dir': '_i5/0' },
    { 'url': 'http://localhost:3000/api/', 'extra': '', 'sid': '0', 'dir': '_i5/1' },
    { 'url': 'http://localhost:3000/assets//', 'extra': '', 'sid': '0', 'dir': '_i5/2' } ]
  },
  { 'severity': 0, 'type': 10402, 'samples': [
    { 'url': 'http://localhost:3000/api/', 'extra': '', 'sid': '0', 'dir': '_i6/0' },
    { 'url': 'http://localhost:8888/api/', 'extra': '', 'sid': '0', 'dir': '_i6/1' } ]
  },
  { 'severity': 0, 'type': 10401, 'samples': [
    { 'url': 'http://localhost:3000/%0A%0A0%8B%A6%0D%B8/', 'extra': '', 'sid': '0', 'dir': '_i7/0' },
    { 'url': 'http://localhost:3000/api/', 'extra': '', 'sid': '0', 'dir': '_i7/1' },
    { 'url': 'http://localhost:8888/api/', 'extra': '', 'sid': '0', 'dir': '_i7/2' } ]
  },
  { 'severity': 0, 'type': 10205, 'samples': [
    { 'url': 'http://localhost:3000/sfi9876', 'extra': '', 'sid': '0', 'dir': '_i8/0' },
    { 'url': 'http://localhost:3000/sfi9876.css', 'extra': '', 'sid': '0', 'dir': '_i8/1' },
    { 'url': 'http://localhost:8888/sfi9876', 'extra': '', 'sid': '0', 'dir': '_i8/2' } ]
  },
  { 'severity': 0, 'type': 10204, 'samples': [
    { 'url': 'http://localhost:3000/api/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i9/0' },
    { 'url': 'http://localhost:3000/api.Avatar/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i9/1' },
    { 'url': 'http://localhost:8888/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i9/2' } ]
  },
  { 'severity': 0, 'type': 10202, 'samples': [
    { 'url': 'http://localhost:3000/', 'extra': 'nginx/1.29.1', 'sid': '0', 'dir': '_i10/0' } ]
  }
];

